sealed class MyOrdersScreenActions{}
class GetActiveOrdersAction extends MyOrdersScreenActions{}
class GetCompletedOrderAction extends MyOrdersScreenActions{}
class GetUserCartItemsAction extends MyOrdersScreenActions{}